### ISSUE TITLE
PRACTICA RECONOCIENTO DE VOZ

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/actividad-10-practica-de-comando-de-voz-equipo-magaly#1]
[PRACTICA RECONOCIMIENTO DE VOZ.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-practica-de-comando-de-voz-equipo-magaly/files/15419768/PRACTICA.RECONOCIMIENTO.DE.VOZ.pdf)

**Comment by josealfredo79** [comment]
Calificacion 20
